---
- name: Copy iptables configuration
  copy:
    src: "iptables-el{{ ansible_distribution_major_version }}"
    dest: '/etc/sysconfig/iptables'
    owner: 'root'
    group: 'root'
  notify:
    - restart iptables

- name: Enable and start iptables service
  service:
    name: 'iptables'
    enabled: true
    state: 'started'

- meta: flush_handlers
